sudo: required
services:
- docker
install:
- set -e
jobs:
  include:
  - stage: unit test
    language: go
    go:
    - 1.11.x
    env:
    - GO111MODULE=on
    - DOCKER_TLS_VERIFY=1
    - secure: U0WHj8cs5dMFrfabxgmhl7Id6UL3+kELfIee7tREvBj3UKZl6iS2P6wA8oQkyvwLH1h+mO0QdTnQqwtH6cUnP1jNHG15loN3KM1504OB64UEv0AnOezrPZLhDQwBWT7T+Rw6iBjBWGUk9KdCuT5/JKlP46ZllRVuMphhtnJwGVggFL+W2ol6oL8qg1/pVT6HZNEwfsbBe3HH3EYw8mhvhM2WjscQKEjiNiIClKwO/IcJdZ0iCUSKvTk20nNIGOnIMfAXtmwMGJAB/nRmHDnzV3ijxyUsCPo6Ae2f/bJsU1The0gCItw9yAag6ckeeudPQtLLRlzZr/Z5l2Z05qWRr7v2BIIVDrs7lBYPUCkoJGy8azCTAnB3BdR0iv/w+6L/p5eK9rHxtW8zI+8rgswfxmAzZjAVDMuIDXXg/PUkK/g27UmzInUmf3gOJk9hItfYtT43hVqp0ZfFTZBtrwOjwVriHKl7o4jGwIkBWWr7UeFzASL0QE45e6yYxlobyuF/plww6ECe/tbGUrXRd52M01VWEqJqHqFZ3v/QUU7ZoYMYLZHAelXrQ9ymIFgBRiXCOCFrofzjMt8KgKEUHre++pBm6E9boUW3mcc6p9Wsi/Mh1cVjr/Fk3T0+4TqTm+Yo2yyabmOCQlRHubLRYcwOdJ9dkXBMIcS7IsQ6szG6kR8=
    go_import_path: github.com/buildpack/lifecycle
    script: |
      openssl aes-256-cbc -K $encrypted_e607085e6307_key -iv $encrypted_e607085e6307_iv -in .travis/key.pem.enc -out .travis/key.pem -d
      test -z "$(bin/format | tee >(cat >&2))"
      export DOCKER_CERT_PATH=$PWD/.travis/
      go test -v ./...
      go test -tags=image -v ./image/...
  - stage: build and push images
    if: branch = master AND fork = false
    env:
    - secure: "ya3FQMvAyu0fWQFO7tTAP9CepONq9cH4Xt3beIdxlUI4kcdwTBDASzMX9QEn5dIPHp2rRy5DuPIB67SqsCQcVA2v2Wmj3d/GVbcTIX8iNpI5T2kFNgoHWH3pLUuigcS22rEImphiLeI+xGDwpG0t3PbTdyx5zc+jASndMxQxmWH9sIJqa6h0i7hqPuaWttBfmnEWR/CWxDI64I49y8C8xOJdN/k+o5R3XK5Qvh70hYH5UIxWF2LwvD3PgcBF+/995ufQmLBMo6XPGWnEdu85UTIj1rAsmh+Ld3b47GKYDXk/jVBcLRTj1jhz/6irDu4/ZpZcb1a9Ocjbcn5LMNzFfi3kPqizZ0buN8w0hS2vfx5mQ1xg9pCzOSw164wyN+4McCEI1fwKujPkbPtiSOkF4GUPBx6w3ezRFZO6a50jQQNVDP24nVD5Q+N8cUcGIFfcaNmyv8noxAsB2shAgEHycYId6ufGoJhdTt40tDGilSvqTGhQKiSWxg9k0VJpsmlXRxfEfaaTkpQowKPtzUsTjfeH14mI2EsZ8AJsv8V9mdWvkJE0tg8DPsCZ8sDbB9gK0VHExRBkcgmlU6+c3/qvitojSEBAD8CSUS8dRCwoTn8PKB1k9BndO9rhLkSlu9SKl8XFbgGYW5hW+gQYsIUz5iswA3EL0FyjGNjavzTtAqw="
    - secure: "McMI5lalBxrsns6ZlekhwqQM0y8h2db3M49KppGVgCD3ShsKubQ14RLRT8tqs60f+UBVzEaMarqNXcSLcCiegH+gMbJazYGVog3vVt8m1AbQEQiSecuQ3GRW00jrjPOU82wJPmj3Xw/L4Pi9PKN+Fmol802gbZMQ69OhLAjiNic0jW+HJ4ZFxrD2ns4BmdMeBURGamZeyMsG3ISzgGfl+LoanV92N7de2bRl3tG88qquyrlVjOK5G+wmp+AK+LdeDly94kSrq1/Pgvpq5xIjK+5bdtn5cIEWaMPtfeKMU+UQjIWVWWU4BQ6ZdktKz6BumP1VGyP9JfNdH269e6UG/KM75QQEDAsv9Daq/oy2WEKMjs4LGv9OOsdzwPRrxOt+EWHwVOOXOXfhYMw5v250naqXAsZmO4PsUqmz8JsTuIVRttZX761d4f/JuPNpeE7GgxTc9D4VxziIl6ksDHrpRRQW4Hc4fznhBsUF7lyomCrwAWYSsZP4YBTYdykgKf0nNmf+iskzoIZfPuvzvWIim0K+ax5vp9B9ocd1mwQd5zPoAoYZRGhipw7d2hbkf8h8dakKdY8y/nBzomfXW1+4LFuuKSyELZg0z0rGu4t/jW6gHuILGCvPqBtCNIRTQSvLwk7Gzt/lKqZOv9P6Luh/UCI+mq+/lWyBy9zYUP0Swpc="
    script:
    - images/bin/build -v "0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "packs/base:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/build:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/run:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/samples:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
  - stage: build and publish v3alpha2 images
    if: branch = v3alpha2
    env:
    - secure: "ya3FQMvAyu0fWQFO7tTAP9CepONq9cH4Xt3beIdxlUI4kcdwTBDASzMX9QEn5dIPHp2rRy5DuPIB67SqsCQcVA2v2Wmj3d/GVbcTIX8iNpI5T2kFNgoHWH3pLUuigcS22rEImphiLeI+xGDwpG0t3PbTdyx5zc+jASndMxQxmWH9sIJqa6h0i7hqPuaWttBfmnEWR/CWxDI64I49y8C8xOJdN/k+o5R3XK5Qvh70hYH5UIxWF2LwvD3PgcBF+/995ufQmLBMo6XPGWnEdu85UTIj1rAsmh+Ld3b47GKYDXk/jVBcLRTj1jhz/6irDu4/ZpZcb1a9Ocjbcn5LMNzFfi3kPqizZ0buN8w0hS2vfx5mQ1xg9pCzOSw164wyN+4McCEI1fwKujPkbPtiSOkF4GUPBx6w3ezRFZO6a50jQQNVDP24nVD5Q+N8cUcGIFfcaNmyv8noxAsB2shAgEHycYId6ufGoJhdTt40tDGilSvqTGhQKiSWxg9k0VJpsmlXRxfEfaaTkpQowKPtzUsTjfeH14mI2EsZ8AJsv8V9mdWvkJE0tg8DPsCZ8sDbB9gK0VHExRBkcgmlU6+c3/qvitojSEBAD8CSUS8dRCwoTn8PKB1k9BndO9rhLkSlu9SKl8XFbgGYW5hW+gQYsIUz5iswA3EL0FyjGNjavzTtAqw="
    - secure: "McMI5lalBxrsns6ZlekhwqQM0y8h2db3M49KppGVgCD3ShsKubQ14RLRT8tqs60f+UBVzEaMarqNXcSLcCiegH+gMbJazYGVog3vVt8m1AbQEQiSecuQ3GRW00jrjPOU82wJPmj3Xw/L4Pi9PKN+Fmol802gbZMQ69OhLAjiNic0jW+HJ4ZFxrD2ns4BmdMeBURGamZeyMsG3ISzgGfl+LoanV92N7de2bRl3tG88qquyrlVjOK5G+wmp+AK+LdeDly94kSrq1/Pgvpq5xIjK+5bdtn5cIEWaMPtfeKMU+UQjIWVWWU4BQ6ZdktKz6BumP1VGyP9JfNdH269e6UG/KM75QQEDAsv9Daq/oy2WEKMjs4LGv9OOsdzwPRrxOt+EWHwVOOXOXfhYMw5v250naqXAsZmO4PsUqmz8JsTuIVRttZX761d4f/JuPNpeE7GgxTc9D4VxziIl6ksDHrpRRQW4Hc4fznhBsUF7lyomCrwAWYSsZP4YBTYdykgKf0nNmf+iskzoIZfPuvzvWIim0K+ax5vp9B9ocd1mwQd5zPoAoYZRGhipw7d2hbkf8h8dakKdY8y/nBzomfXW1+4LFuuKSyELZg0z0rGu4t/jW6gHuILGCvPqBtCNIRTQSvLwk7Gzt/lKqZOv9P6Luh/UCI+mq+/lWyBy9zYUP0Swpc="
    script:
    - images/bin/build -v "v3alpha2"
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "packs/base:v3alpha2"
    - docker push "packs/build:v3alpha2"
    - docker push "packs/run:v3alpha2"
    - docker push "packs/samples:v3alpha2"
    - docker tag "packs/base:v3alpha2" "packs/base:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker tag "packs/build:v3alpha2" "packs/build:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker tag "packs/run:v3alpha2" "packs/run:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker tag "packs/samples:v3alpha2" "packs/samples:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/base:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/build:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/run:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
    - docker push "packs/samples:0.0.1-rc.$TRAVIS_BUILD_NUMBER"
